export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const SET_OPEN_MODAL = 'SET_OPEN_MODAL';

export const DELETE_MOVIE = 'DELETE_MOVIE';